# Generated by Django 5.0.4 on 2024-04-24 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fileupload',
            old_name='user_id',
            new_name='user',
        ),
    ]
