# Generated by Django 4.2.13 on 2024-06-16 07:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0003_dataupload'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgeGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agegroup', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Complication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Indication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RotatorCuffPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologies', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyRevisionRateBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyRevisionRateByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyByComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.complication')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='RevisionRatesOfProsthesisCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arthrex', models.IntegerField()),
                ('depuy_synthes', models.IntegerField(verbose_name='DePuy Synthes')),
                ('smith_nephew', models.IntegerField(verbose_name='Smith & Nephew')),
                ('stryker', models.IntegerField()),
                ('zimmer_biomet', models.IntegerField(verbose_name='Zimmer Biomet')),
                ('exacthech', models.IntegerField(verbose_name='Exacthech')),
                ('lima', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
            options={
                'verbose_name_plural': 'Revision Rate of Prosthesis Company',
            },
        ),
        migrations.CreateModel(
            name='ReverseTotalShoulderArthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseTotalShoulderArthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ProsthesisCompanyFrequencyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arthrex', models.IntegerField()),
                ('depuy_synthes', models.IntegerField(verbose_name='DePuy Synthes')),
                ('smith_nephew', models.IntegerField(verbose_name='Smith & Nephew')),
                ('stryker', models.IntegerField()),
                ('zimmer_biomet', models.IntegerField(verbose_name='Zimmer Biomet')),
                ('exacthech', models.IntegerField(verbose_name='Exacthech')),
                ('lima', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
            options={
                'verbose_name_plural': 'Prosthesis Company Frequencies by indication',
            },
        ),
        migrations.CreateModel(
            name='ProsthesisCompanyFrequency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arthrex', models.IntegerField()),
                ('depuy_synthes', models.IntegerField(verbose_name='DePuy Synthes')),
                ('smith_nephew', models.IntegerField(verbose_name='Smith & Nephew')),
                ('stryker', models.IntegerField()),
                ('zimmer_biomet', models.IntegerField(verbose_name='Zimmer Biomet')),
                ('exacthech', models.IntegerField(verbose_name='Exacthech')),
                ('lima', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('age_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.agegroup')),
            ],
            options={
                'verbose_name_plural': 'Prosthesis Company Frequencies by Age',
            },
        ),
        migrations.CreateModel(
            name='PrevalenceOfPatientsWithRotatorcuffPathologyWith_GreaterEqual_1_comorbiditieByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='PrevalenceOfNeerThreeOrFour_partProximalHumeralFractureByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='HemiarthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
        migrations.CreateModel(
            name='HemiarthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='AnatomicTotalShoulderArthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
        migrations.CreateModel(
            name='AnatomicTotalShoulderArthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
    ]
