# Generated by Django 5.0.4 on 2024-04-25 05:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_rename_user_id_fileupload_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sex', models.CharField(max_length=255)),
                ('age', models.CharField(max_length=255)),
                ('indications', models.CharField(max_length=255)),
                ('prothesis_type', models.CharField(max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='fileupload.fileupload')),
            ],
        ),
    ]
