# Generated by Django 5.0.4 on 2024-05-16 05:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0008_prosthesiscompanyfrequency_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prosthesiscompanyfrequency',
            options={'verbose_name_plural': 'Prosthesis Company Frequencies by Age'},
        ),
        migrations.AlterModelOptions(
            name='prosthesiscompanyfrequencybyindication',
            options={'verbose_name_plural': 'Prosthesis Company Frequencies by indication'},
        ),
        migrations.AlterModelOptions(
            name='revisionratesofprosthesiscompany',
            options={'verbose_name_plural': 'Revision Rate of Prosthesis Company'},
        ),
        migrations.CreateModel(
            name='HemiarthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
    ]
