# Generated by Django 5.0.4 on 2024-05-21 08:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0009_alter_prosthesiscompanyfrequency_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnatomicTotalShoulderArthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='AnatomicTotalShoulderArthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
        migrations.CreateModel(
            name='HemiarthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='PrevalenceOfNeerThreeOrFour_partProximalHumeralFractureByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='PrevalenceOfPatientsWithRotatorcuffPathologyWith_GreaterEqual_1_comorbiditieByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseTotalShoulderArthroplastyByAgeAndSex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zero_19', models.IntegerField()),
                ('twenty_39', models.IntegerField()),
                ('forty_59', models.IntegerField()),
                ('sixty_79', models.IntegerField()),
                ('greaterThan_80', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ReverseTotalShoulderArthroplastyByIndication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('indication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.indication')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyByComplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('complication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.complication')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyRevisionRateByAge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('age', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.agegroup')),
            ],
        ),
        migrations.CreateModel(
            name='ShoulderArthroplastyRevisionRateBySex',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hemiarthroplasty', models.IntegerField()),
                ('AnatomicTotalShoulderArthroplasty', models.IntegerField()),
                ('ReverseTotalShoulderArthroplasty', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('sex', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='fileupload.sex')),
            ],
        ),
    ]
