# Generated by Django 5.0.4 on 2024-05-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0010_anatomictotalshoulderarthroplastybyageandsex_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RotatorCuffPathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathologies', models.CharField(max_length=255)),
                ('count', models.IntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
