# Generated by Django 5.0.4 on 2024-05-24 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0011_rotatorcuffpathology'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agegroup',
            old_name='name',
            new_name='agegroup',
        ),
    ]
